import { describe, expect, it } from 'vitest';

import { classifyTerminalAgentCli } from './TerminalAgentCliMetadata';

describe('classifyTerminalAgentCli', () => {
  it.each([
    ['codex', 'codex'],
    ['CODEX.EXE', 'codex'],
    ['claude', 'claude'],
    ['Claude.cmd', 'claude'],
    ['opencode', 'opencode'],
    ['OpenCode.BAT', 'opencode'],
    ['kimi', 'kimi'],
    ['KIMI.exe', 'kimi'],
    ['kimi-cli', 'kimi'],
    ['KIMI-CLI.cmd', 'kimi'],
    ['gemini', 'gemini'],
    ['Gemini.CMD', 'gemini'],
    ['qwen', 'qwen'],
    ['QWEN.bat', 'qwen'],
    ['copilot', 'copilot'],
    ['Copilot.exe', 'copilot'],
    ['cline', 'cline'],
    ['Cline.BAT', 'cline'],
    ['roo', 'roo'],
    ['ROO.exe', 'roo'],
    ['vibe', 'vibe'],
    ['Vibe.cmd', 'vibe'],
    ['cursor-agent', 'cursor'],
    ['CURSOR-AGENT.BAT', 'cursor'],
    ['junie', 'junie'],
    ['Junie.cmd', 'junie'],
    ['kiro-cli', 'kiro'],
    ['KIRO-CLI.BAT', 'kiro'],
    ['openhands', 'openhands'],
    ['OpenHands.exe', 'openhands'],
    ['trae-cli', 'trae'],
    ['TRAE-CLI.cmd', 'trae'],
    ['kilocode', 'kilo'],
    ['KILOCODE.BAT', 'kilo'],
  ] as const)('classifies exact agent CLI basename %s', (displayName, expected) => {
    expect(classifyTerminalAgentCli(displayName)).toBe(expected);
  });

  it.each([
    '',
    'my-codex',
    'claude-helper',
    'opencode-dev',
    'kimicode',
    '/usr/bin/codex',
    'codex --help',
    'codex.sh',
    'gemini-cli',
    'qwen-code',
    'github-copilot',
    'goose',
    'goose-cli',
    'cline-agent',
    'roocode',
    'mistral-vibe',
    'cursor',
    'amp',
    'ampcode',
    'junie-cli',
    'kiro',
    'open-hands',
    'trae',
    'trae-agent',
    'kilo',
    'kilo-code',
    'agent',
    'q',
    'cn',
    '工具',
    'x'.repeat(65),
    null,
    undefined,
  ])('does not guess an agent identity from %j', (displayName) => {
    expect(classifyTerminalAgentCli(displayName)).toBeNull();
  });
});
